### ISSUE TITLE
{{CompatEdge}}: version reporting inconsistent with MS feature changelog conventions

### ISSUE THREAD

**Issue by Artoria2e5** [mozilla/kumascript#130]
Unlike the approach this template uses, Microsoft usually uses five-digit build numbers instead of a more marketable build number when it comes to [writing changelogs](https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/) and [reporting features](https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/). These monotonic build numbers establish a one-to-one mapping from/to an EdgeHTML version, an Edge version, and (for now) an associated Windows release.

Switching to the build number is more or less more useful to developers who actually use cutting-edge versions of Edge as it unifies the two version numbers and is closer to Microsoft-speak.

**Comment by wbamberg** [comment]
Thanks for the bug, but we decided in the end not to use this version format for Edge: https://github.com/mozilla/kumascript/pull/131#issuecomment-291992318
