### ISSUE TITLE
Modify SauceLabsPromo to handle localization

### ISSUE THREAD

**Issue by SphinxKnight** [mozilla/kumascript#153]
Currently the [SauceLabsPromo macro](https://github.com/mozilla/kumascript/blob/master/macros/SauceLabsPromo.ejs) cannot be localized easily. One could use the mdn.localString system which is used on other macros.

For example, the DevTools' landing page in French displays a pretty large block of English.

**Comment by jwhitlock** [comment]
@jpetto - was there a localization requirement for the sauce labs demo?

**Comment by jpetto** [comment]
No, it was intended to be in English only. See [Vik's comment in the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1330094#c10).

**Comment by jwhitlock** [comment]
The comment seems pretty clear to me - English-only, and show it to everyone.  If you want a clarification or exception for https://developer.mozilla.org/fr/docs/Outils, I think it should be argued on [bug 1330094](https://bugzilla.mozilla.org/show_bug.cgi?id=1330094) first.

**Comment by SphinxKnight** [comment]
Ok, thanks John, Jon :)
