### ISSUE TITLE
{{LegacyAddonsNotice}} should mention mobile

### ISSUE THREAD

**Issue by timdream** [mozilla/kumascript#167]
Given that we are not turning off legacy add-ons on Fennec 57, we should make it clear in the `{{LegacyAddonsNotice}}`.

**Comment by atsay** [comment]
@andymckay Can you comment on this, and what would make the message more accurate? I'd tag Joe but I don't see him in the drop-down.

**Comment by andymckay** [comment]
We are not turning off legacy add-ons on Fennec 57.

**Comment by jwhitlock** [comment]
Here's a page with the current notice text:

https://developer.mozilla.org/en-US/Add-ons/Code_snippets/getAttributeNS

It does link to this blog article for more information, which appears to have been updated:

https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/

You could suggest new text by opening a pull request against [LegacyAddonsNotice](https://github.com/mozilla/kumascript/blob/master/macros/LegacyAddonsNotice.ejs#L4-L19).  It may be possible to make the change and open a PR just using the GitHub web interface.  Or you could suggest new wording in this bug.

**Comment by andymckay** [comment]
I think we should fix up those sources to be more accurate, it wasn't the intention to suggest that Android is going WebExtension only in Firefox 57.

**Comment by wbamberg** [comment]
I can definitely add something to the effect that this notice only applies to desktop Firefox. But I do think Mozilla needs to communicate the plans for mobile. The main source of info is this https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/ and it doesn't mention mobile at all.

**Comment by jvillalobos** [comment]
After some discussion, we have concluded to include Android in the same plan:
https://blog.mozilla.org/addons/2017/05/18/compatibility-update-android/

**Comment by atsay** [comment]
Will assign to @andrewtruongmoz and scope in Thursday's documentation meeting.

**Comment by andrewtruongmoz** [comment]
A draft for this has been started. It is not complete but just a starting point. 

https://docs.google.com/a/mozilla.com/document/d/1F69jKWi660zEw6jb2Fh5Ts6s_D8yhV1Taz8nBGav6so/edit?usp=sharing

**Comment by wbamberg** [comment]
Hi Andrew (welcome!)

If it helps, here's a hierarchical list of all pages under https://developer.mozilla.org/Add-ons:

[https://developer.mozilla.org/en-US/docs/User:wbamberg/all-addons-pages](https://developer.mozilla.org/en-US/docs/User:wbamberg/all-addons-pages)

**Comment by wbamberg** [comment]
This notice is now updated to describe the Firefox for Android situation.
