### ISSUE TITLE
{{EventRef}} macro has started throwing errors

### ISSUE THREAD

**Issue by chrisdavidmills** [mozilla/kumascript#176]
For example see:

* https://developer.mozilla.org/en-US/docs/Web/Events/statechange_(cancellable_fetch)
* https://developer.mozilla.org/en-US/docs/Web/Events/responseprogress
* https://developer.mozilla.org/en-US/docs/Web/Events/requestprogress
* https://developer.mozilla.org/en-US/docs/Web/Events

The error is 

```Problem executing template EventRef:
    1 | <div>{{EventRef}}{{SeeCompatTable}}</div>
-------------^
    2 | 
    3 | <div>

TypeError: ejs:1
 >> 1| <%
    2| // Event Sidebar
    3| //
    4| 

Cannot read property 'indexOf' of undefined
    at eval (eval at compile (/data/www/developer.mozilla.org/kuma/kumascript/node_modules/ejs/lib/ejs.js:491:12), <anonymous>:44:22)
    at returnedFn (/data/www/developer.mozilla.org/kuma/kumascript/node_modules/ejs/lib/ejs.js:520:17)
    at /data/www/developer.mozilla.org/kuma/kumascript/lib/kumascript/templates.js:69:30
```

**Comment by escattone** [comment]
This is fixed via an MDN production push today at 11:26am PST. Thanks @chrisdavidmills and @Elchi3 !
