### ISSUE TITLE
csssyntax errors

### ISSUE THREAD

**Issue by wbamberg** [mozilla/kumascript#269]
Some CSS pages are getting errors from the {{csssyntax}} macro. Not all of them, but at least:

https://developer.mozilla.org/en-US/docs/Web/CSS/attr
https://developer.mozilla.org/en-US/docs/Web/CSS/calc
https://developer.mozilla.org/en-US/docs/Web/CSS/minmax

I haven't tried refreshing every page yet though, so there are probably more.

**Comment by jwhitlock** [comment]
Fix pushed to production, and the pages regenerate cleanly.
