### ISSUE TITLE
Runtime configuration management

### ISSUE THREAD

**Issue by lmorchard** [mozilla/kumascript#40]
Currently, the configuration for Kumascript as deployed in Kuma happens in a `kumascript_settings_local.json` file that is editable only by IT. This works fine for settings that are infrastructure related (ie. the IP to a memcache server), but not so much for tuning settings (ie. the timeout duration before terminating a hung worker process).

On the Kuma side of things, we have django-constance that lets us alter some runtime settings for the site that does not require attention from IT folks. It would be nice if KumaScript had some settings that could be altered in this way.

**Comment by Mrvipvegas** [comment]
Coming to see
